const db = require('./db');
const { LevelGenerator } = require('./public/js/LevelGenerator');

async function runTests() {
  console.log('================================================================');
  console.log('🧪 RUNNING COMPREHENSIVE UNIFIED LEADERBOARD & RESTORE TESTS');
  console.log('================================================================\n');

  // Test 1: Restore snapshot 1791149202825
  console.log('Test 1: Restoring snapshot 1791149202825...');
  const res = await db.restoreLeaderboardSnapshot('1791149202825');
  console.log('✅ Restore returned:', res);

  if (!res || !res.success) throw new Error('Restore failed!');
  if (res.totalPlayers !== 26) throw new Error(`Expected 26 players, got ${res.totalPlayers}`);

  // Test 2: Verify active leaderboard in SQLite
  console.log('\nTest 2: Verifying active leaderboard in SQLite...');
  const lb = db.getLeaderboard(null, 50);
  console.log(`Active leaderboard total players: ${lb.topPlayers.length}`);
  if (lb.topPlayers.length !== 26) {
    throw new Error(`Expected 26 active players in leaderboard, found ${lb.topPlayers.length}`);
  }

  // Verify top players
  const top1 = lb.topPlayers[0];
  console.log(`Rank 1: ${top1.first_name} (TID: ${top1.telegram_id}) - Level ${top1.max_level}`);
  if (top1.first_name !== 'ALLIGATOR' || top1.max_level !== 48) {
    throw new Error(`Expected ALLIGATOR at level 48, got ${top1.first_name} at ${top1.max_level}`);
  }

  const top2 = lb.topPlayers[1];
  console.log(`Rank 2: ${top2.first_name} (TID: ${top2.telegram_id}) - Level ${top2.max_level}`);
  if (top2.first_name !== 'Руслан' || top2.max_level !== 47) {
    throw new Error(`Expected Руслан at level 47, got ${top2.first_name} at ${top2.max_level}`);
  }

  // Test 3: Annulment of non-snapshot players (rollback simulation)
  console.log('\nTest 3: Simulating a non-snapshot player (ghost/new) before restore...');
  // Insert a test user with high level not in snapshot
  const dummyTid = '9999999999';
  db.db.prepare(`
    INSERT OR REPLACE INTO users (telegram_id, first_name, username, max_level, current_level, stars)
    VALUES (?, 'GhostPlayer', 'ghost', 99, 99, 100)
  `).run(dummyTid);

  let checkBefore = db.getLeaderboard(dummyTid, 50);
  const foundGhostBefore = checkBefore.topPlayers.find(p => p.telegram_id === dummyTid);
  console.log('Ghost player present in active leaderboard before restore:', !!foundGhostBefore);
  if (!foundGhostBefore) throw new Error('Ghost player should have been in leaderboard before restore');

  // Now restore snapshot 1791149202825 again
  console.log('Re-restoring snapshot 1791149202825 to verify ghost player is completely wiped...');
  await db.restoreLeaderboardSnapshot('1791149202825');

  const checkAfter = db.getLeaderboard(dummyTid, 50);
  const foundGhostAfter = checkAfter.topPlayers.find(p => p.telegram_id === dummyTid);
  console.log('Ghost player present in active leaderboard after restore:', !!foundGhostAfter);
  if (foundGhostAfter) throw new Error('Ghost player MUST be wiped from leaderboard after restore!');

  // Check ghost user in users table has max_level = 0
  const ghostUser = db.getUser(dummyTid);
  console.log(`Ghost user max_level: ${ghostUser.max_level}, current_level: ${ghostUser.current_level}`);
  if (ghostUser.max_level !== 0) throw new Error('Ghost user max_level must be reset to 0');

  // Clean up dummy user
  db.db.prepare(`DELETE FROM users WHERE telegram_id = ?`).run(dummyTid);

  // Test 4: Bottle count corresponds strictly to player level
  console.log('\nTest 4: Verifying bottle counts generated by LevelGenerator...');
  const testLevels = [1, 5, 10, 20, 30, 48];
  testLevels.forEach(lvl => {
    const config = LevelGenerator.generateLevel(lvl);
    console.log(`Level ${lvl.toString().padStart(2, ' ')}: Total Bottles = ${config.bottles.length} (${config.colorCount} colors + empty jars)`);
    if (lvl === 1 && config.bottles.length !== 7) throw new Error(`Level 1 should have 7 bottles, got ${config.bottles.length}`);
    if (lvl === 30 && config.bottles.length !== 20) throw new Error(`Level 30 should have 20 bottles, got ${config.bottles.length}`);
    if (lvl === 48 && config.bottles.length !== 24) throw new Error(`Level 48 should have 24 bottles, got ${config.bottles.length}`);
  });

  // Test 5: Verify getLeaderboardRestoredTimestamp
  console.log('\nTest 5: Verifying restored timestamp...');
  const restoredTs = db.getLeaderboardRestoredTimestamp();
  const activeSnap = db.getActiveSnapshotId();
  console.log(`Restored timestamp: ${restoredTs} (${new Date(restoredTs).toISOString()})`);
  console.log(`Active snapshot ID: ${activeSnap}`);
  if (restoredTs <= 0) throw new Error('Restored timestamp should be > 0');
  if (activeSnap !== '1791149202825') throw new Error(`Expected active snapshot 1791149202825, got ${activeSnap}`);

  console.log('\n================================================================');
  console.log('🎉 ALL INTEGRATION TESTS PASSED 100% SUCCESSFULLY!');
  console.log('================================================================');
}

runTests().catch(err => {
  console.error('TEST FAILURE:', err);
  process.exit(1);
});
